export const SUPPORTED_LOCALES = ['en', 'zh-CN'];
export const DEFAULT_LOCALE = 'en';

const ESCAPE_MAP = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };

export function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, (character) => ESCAPE_MAP[character]);
}

// One catalog feeds renderer-time SVG/HTML copy and the selected runtime
// catalog embedded in each standalone artifact. Keeping every locale in one
// tuple makes missing translations impossible to hide behind an English
// fallback during development.
const MESSAGE_PAIRS = {
  'page.title': ['{title} Diagram', '{title}'],
  'diagram.description.architecture': ['An architecture diagram generated by Archify.', '由 Archify 生成的架构图。'],
  'diagram.description.workflow': ['A workflow diagram generated by Archify.', '由 Archify 生成的工作流图。'],
  'diagram.description.sequence': ['A sequence diagram generated by Archify.', '由 Archify 生成的时序图。'],
  'diagram.description.dataflow': ['A data-flow diagram generated by Archify.', '由 Archify 生成的数据流图。'],
  'diagram.description.lifecycle': ['A lifecycle diagram generated by Archify.', '由 Archify 生成的生命周期图。'],
  'node.focus': ['Focus {label}', '聚焦{label}'],
  'node.focus.detail': ['Focus {label}, {detail}', '聚焦{label}，{detail}'],
  'node.context.architecture': ['Architecture component', '架构组件'],
  'node.context.workflow': ['Workflow node', '工作流节点'],
  'node.context.sequence': ['Sequence participant', '时序参与者'],
  'node.context.dataflow': ['Data-flow node', '数据流节点'],
  'node.context.lifecycle': ['Lifecycle state', '生命周期状态'],

  'viewer.kind.frontend': ['Frontend', '前端'],
  'viewer.kind.backend': ['Backend', '后端'],
  'viewer.kind.database': ['Database', '数据库'],
  'viewer.kind.cloud': ['Cloud', '云服务'],
  'viewer.kind.security': ['Security', '安全'],
  'viewer.kind.messagebus': ['Message bus', '消息总线'],
  'viewer.kind.external': ['External', '外部系统'],
  'viewer.kind.entrypoint': ['Entrypoint', '入口'],
  'viewer.kind.owner': ['Owner', '所有者'],
  'viewer.kind.candidate': ['Candidate', '候选'],
  'viewer.kind.consumer': ['Consumer', '消费者'],
  'viewer.kind.state': ['State', '状态'],
  'viewer.kind.store': ['Store', '存储'],
  'viewer.kind.boundary': ['Boundary', '边界'],
  'viewer.kind.neutral': ['Neutral', '中性'],
  'viewer.kind.node': ['Node', '节点'],
  'viewer.kind.start': ['Start', '开始'],
  'viewer.kind.active': ['Active', '活动'],
  'viewer.kind.waiting': ['Waiting', '等待'],
  'viewer.kind.decision': ['Decision', '决策'],
  'viewer.kind.success': ['Success', '成功'],
  'viewer.kind.failure': ['Failure', '失败'],

  'viewer.toolbar.actions': ['Diagram actions', '图表操作'],
  'viewer.theme.toggle.title': ['Toggle theme (T)', '切换主题（T）'],
  'viewer.theme.toggle': ['Toggle color theme', '切换颜色主题'],
  'viewer.theme.dark': ['Dark', '深色'],
  'viewer.theme.light': ['Light', '浅色'],

  'viewer.export.button': ['Export', '导出'],
  'viewer.export.button.title': ['Export diagram (E)', '导出图表（E）'],
  'viewer.export.diagram': ['Export diagram', '导出图表'],
  'viewer.export.menu': ['Export', '导出'],
  'viewer.export.subtitle': ['Portable, clean outputs', '便携、整洁的输出'],
  'viewer.export.share': ['Share', '分享'],
  'viewer.export.shareCard': ['Share Card', '分享卡片'],
  'viewer.export.routeShareCard': ['Route Share Card', '路径分享卡片'],
  'viewer.export.reachShareCard': ['Reach Share Card', '可达范围分享卡片'],
  'viewer.export.copyShareCard': ['Copy Share Card', '复制分享卡片'],
  'viewer.export.copyDiagram': ['Copy diagram', '复制图表'],
  'viewer.export.clipboardPng': ['PNG to clipboard', '复制 PNG 到剪贴板'],
  'viewer.export.raster': ['Raster images', '位图'],
  'viewer.export.image': ['Image', '图像'],
  'viewer.export.lossless': ['Lossless image', '无损图像'],
  'viewer.export.compact': ['Compact image', '紧凑图像'],
  'viewer.export.modern': ['Modern image', '现代图像格式'],
  'viewer.export.vector': ['Vector image', '矢量图像'],
  'viewer.export.vector.heading': ['Vector', '矢量'],
  'viewer.export.editable': ['Editable vector', '可编辑矢量图'],
  'viewer.export.unsupported': ['Not supported by this browser', '当前浏览器不支持'],
  'viewer.export.clipboardUnsupported': ['Clipboard image write not supported by this browser', '当前浏览器不支持写入图片剪贴板'],
  'viewer.export.clipboardUnsupported.period': ['Clipboard image write not supported by this browser.', '当前浏览器不支持写入图片剪贴板。'],
  'viewer.export.clipboardUnsupported.short': ['Clipboard image write not supported in this browser.', '此浏览器不支持写入图片剪贴板。'],
  'viewer.export.failed': ['Export failed: {message}', '导出失败：{message}'],
  'viewer.export.unknownVariant': ['Unknown Share Card variant: {variant}', '未知的分享卡片类型：{variant}'],
  'viewer.export.routeRequired': ['Trace a route before exporting a Route Share Card', '请先追踪路径，再导出路径分享卡片'],
  'viewer.export.reachRequired': ['Trace authored reach before exporting a Reach Share Card', '请先追踪编写可达范围，再导出可达范围分享卡片'],
  'viewer.export.unknown': ['unknown', '未知错误'],
  'viewer.export.routeFailed': ['Route Share Card export failed: {message}', '路径分享卡片导出失败：{message}'],
  'viewer.export.reachFailed': ['Reach Share Card export failed: {message}', '可达范围分享卡片导出失败：{message}'],
  'viewer.export.copyFailed': ['Copy failed: {message}', '复制失败：{message}'],
  'viewer.export.copiedPng': ['Copied PNG to clipboard', '已将 PNG 复制到剪贴板'],
  'viewer.export.copiedShare': ['Copied Share Card', '已复制分享卡片'],
  'viewer.export.downloadedShare': ['Downloaded Share Card', '已下载分享卡片'],
  'viewer.export.downloadedRoute': ['Downloaded Route Share Card', '已下载路径分享卡片'],
  'viewer.export.downloadedReach': ['Downloaded Reach Share Card', '已下载可达范围分享卡片'],
  'viewer.export.card.routeSummary.one': ['Route: {source} → {target} · {count} directed hop', '路径：{source} → {target} · {count} 个有向跳转'],
  'viewer.export.card.routeSummary.other': ['Route: {source} → {target} · {count} directed hops', '路径：{source} → {target} · {count} 个有向跳转'],
  'viewer.export.card.reachSummary': ['Authored {direction} from {origin} · {nodes} · {links} · max {hops}', '从{origin}开始的编写{direction} · {nodes} · {links} · 最深 {hops}'],
  'viewer.export.card.node.one': ['{count} node', '{count} 个节点'],
  'viewer.export.card.node.other': ['{count} nodes', '{count} 个节点'],
  'viewer.export.card.link.one': ['{count} link', '{count} 条连接'],
  'viewer.export.card.link.other': ['{count} links', '{count} 条连接'],
  'viewer.export.card.hop.one': ['{count} hop', '{count} 跳'],
  'viewer.export.card.hop.other': ['{count} hops', '{count} 跳'],
  'viewer.export.card.routeBadge': ['ARCHIFY · ROUTE · {hops}', 'ARCHIFY · 路径 · {hops}'],
  'viewer.export.card.reachBadge': ['ARCHIFY · {direction} REACH', 'ARCHIFY · {direction}可达范围'],
  'viewer.export.card.defaultBadge': ['ARCHIFY · SIGNAL FLOW · {theme}', 'ARCHIFY · 信号流 · {theme}'],
  'viewer.export.direction.upstream': ['Upstream', '上游'],
  'viewer.export.direction.downstream': ['Downstream', '下游'],
  'viewer.export.error.canvasUnavailable': ['Canvas unavailable for {label}', '无法为{label}使用画布'],
  'viewer.export.error.contextUnavailable': ['2D canvas context unavailable for {label}', '无法为{label}创建二维画布上下文'],
  'viewer.export.error.toBlobUnavailable': ['canvas.toBlob unavailable for {label}', '{label}无法使用 canvas.toBlob'],
  'viewer.export.error.toBlobNull': ['canvas.toBlob returned no data for {label}', '{label}的 canvas.toBlob 未返回数据'],
  'viewer.export.error.variantsCombined': ['Share Card variants cannot be combined', '无法同时组合多种分享卡片类型'],
  'viewer.export.error.viewerState': ['Share Card export could not remove temporary viewer state', '分享卡片导出无法移除临时 Viewer 状态'],
  'viewer.export.error.routeState': ['Route Card export could not preserve the resolved route safely', '路径卡片导出无法安全保留已解析路径'],
  'viewer.export.error.reachState': ['Reach Card export could not preserve authored reach safely', '可达范围卡片导出无法安全保留编写的可达范围'],


  'viewer.finder.title': ['Find a node', '查找节点'],
  'viewer.finder.close': ['Close node finder', '关闭节点查找器'],
  'viewer.finder.placeholder': ['Search labels or IDs', '搜索标签或 ID'],
  'viewer.finder.search': ['Search diagram nodes', '搜索图表节点'],
  'viewer.finder.results': ['Diagram nodes', '图表节点'],
  'viewer.finder.empty': ['No matching nodes', '没有匹配的节点'],
  'viewer.finder.result.focus': ['Focus {label}', '聚焦{label}'],
  'viewer.finder.result.routeStart': ['Choose {label} as route start', '选择{label}作为路径起点'],
  'viewer.finder.result.routeTarget': ['Choose {label} as route destination, {links}', '选择{label}作为路径终点，{links}'],
  'viewer.finder.status.empty': ['No matching nodes', '没有匹配的节点'],
  'viewer.finder.status.count.one': ['{count} matching node', '{count} 个匹配节点'],
  'viewer.finder.status.count.other': ['{count} matching nodes', '{count} 个匹配节点'],
  'viewer.finder.noun.nodes': ['nodes', '个节点'],
  'viewer.finder.link.one': ['{count} link', '{count} 条连接'],
  'viewer.finder.link.other': ['{count} links', '{count} 条连接'],
  'viewer.finder.result.focus.one': ['Focus {label}, {count} related connection', '聚焦{label}，{count} 条相关连接'],
  'viewer.finder.result.focus.other': ['Focus {label}, {count} related connections', '聚焦{label}，{count} 条相关连接'],
  'viewer.finder.status.filtered': ['{visible} of {available} {noun}', '{visible}/{available} {noun}'],
  'viewer.finder.status.all': ['{available} {noun}', '{available} {noun}'],
  'viewer.focus.selectedNodes': ['{count} selected nodes', '已选择 {count} 个节点'],

  'viewer.passport.eyebrow': ['Semantic passport', '语义护照'],
  'viewer.passport.metadata': ['Node metadata', '节点元数据'],
  'viewer.passport.reach': ['Authored reach', '编写可达范围'],
  'viewer.passport.reach.trace': ['Trace authored reachability', '追踪编写的可达性'],
  'viewer.passport.upstream': ['Upstream', '上游'],
  'viewer.passport.downstream': ['Downstream', '下游'],
  'viewer.passport.upstream.trace': ['Trace upstream authored reachability', '追踪上游编写可达性'],
  'viewer.passport.downstream.trace': ['Trace downstream authored reachability', '追踪下游编写可达性'],
  'viewer.passport.close': ['Close semantic passport', '关闭语义护照'],
  'viewer.passport.copy': ['Copy link', '复制链接'],
  'viewer.passport.copy.focus': ['Copy link to focused node', '复制聚焦节点的链接'],
  'viewer.passport.relations': ['Relations', '关系'],
  'viewer.passport.relations.show': ['Show connected relationships', '显示关联关系'],
  'viewer.passport.relations.hide': ['Hide connected relationships', '隐藏关联关系'],
  'viewer.passport.relations.list': ['Connected relationships', '关联关系'],
  'viewer.passport.copyRelation': ['Copy relation', '复制关系'],
  'viewer.passport.copyNode': ['Copy node', '复制节点'],
  'viewer.passport.copyPinned': ['Copy link to pinned relationship', '复制固定关系的链接'],
  'viewer.passport.copySource': ['Copy link to source node', '复制来源节点的链接'],
  'viewer.passport.copy.focused.success': ['Focused node link copied', '已复制聚焦节点链接'],
  'viewer.passport.copy.pinned.success': ['Pinned relationship link copied', '已复制固定关系链接'],
  'viewer.passport.copy.focused.failed': ['Could not copy focused node link', '无法复制聚焦节点链接'],
  'viewer.passport.copy.pinned.failed': ['Could not copy pinned relationship link', '无法复制固定关系链接'],
  'viewer.passport.relationship.none': ['No connected relationships', '没有关联关系'],
  'viewer.passport.relationship.count.one': ['{count} relation', '{count} 条关系'],
  'viewer.passport.relationship.count.other': ['{count} relations', '{count} 条关系'],
  'viewer.passport.relationship.show.one': ['Show {count} connected relationship', '显示 {count} 条关联关系'],
  'viewer.passport.relationship.show.other': ['Show {count} connected relationships', '显示 {count} 条关联关系'],
  'viewer.passport.relationship.summary': ['{out} outgoing · {in} incoming{loops}', '{out} 条出向 · {in} 条入向{loops}'],
  'viewer.passport.relationship.loops': [' · {count} loop', ' · {count} 条自环'],
  'viewer.passport.relationship.explorer': ['Direct relationship explorer', '直接关系浏览器'],
  'viewer.passport.relationship.help': ['Use arrow keys to explore relationships. Press Enter or Space to pin details; Escape clears.', '使用方向键浏览关系。按 Enter 或空格键固定详情；按 Escape 清除。'],
  'viewer.passport.relationship.loopsBack': ['loops back', '回环'],
  'viewer.passport.relationship.connectsTo': ['connects to', '连接到'],
  'viewer.passport.relationship.connectsFrom': ['connects from', '连接自'],
  'viewer.passport.relationship.pinned': ['Pinned relationship · {from} → {to} · {label}', '已固定关系 · {from} → {to} · {label}'],
  'viewer.passport.relationship.inspect': ['Inspect relationship {index} of {total}: {from} to {to}, {label}. Press Enter for details.', '检查第 {index}/{total} 条关系：{from} 到 {to}，{label}。按 Enter 查看详情。'],
  'viewer.passport.relationship.group.out': ['Outgoing', '出向'],
  'viewer.passport.relationship.group.in': ['Incoming', '入向'],
  'viewer.passport.relationship.group.loop': ['Self loops', '自环'],
  'viewer.passport.relationship.row': ['{group}: {relationship}, {neighbor}', '{group}：{relationship}，{neighbor}'],
  'viewer.passport.relationship.direction.out': ['OUT →', '出 →'],
  'viewer.passport.relationship.direction.in': ['← IN', '← 入'],
  'viewer.passport.relationship.direction.loop': ['LOOP', '自环'],
  'viewer.passport.reach.upstream.one': ['Trace {count} upstream authored node', '追踪 {count} 个上游编写节点'],
  'viewer.passport.reach.upstream.other': ['Trace {count} upstream authored nodes', '追踪 {count} 个上游编写节点'],
  'viewer.passport.reach.downstream.one': ['Trace {count} downstream authored node', '追踪 {count} 个下游编写节点'],
  'viewer.passport.reach.downstream.other': ['Trace {count} downstream authored nodes', '追踪 {count} 个下游编写节点'],
  'viewer.passport.reach.noUpstream': ['No upstream authored nodes', '没有上游编写节点'],
  'viewer.passport.reach.noDownstream': ['No downstream authored nodes', '没有下游编写节点'],
  'viewer.passport.reach.status': ['{direction} · {nodes} nodes · {links} links · max {hops} hops', '{direction} · {nodes} 个节点 · {links} 条连接 · 最深 {hops} 跳'],

  'viewer.route.eyebrow': ['Route probe', '路径探测'],
  'viewer.route.start': ['Choose a start node', '选择起点节点'],
  'viewer.route.start.find': ['Find start', '查找起点'],
  'viewer.route.start.find.aria': ['Find a route start', '查找路径起点'],
  'viewer.route.copy': ['Copy link', '复制链接'],
  'viewer.route.copy.aria': ['Copy link to traced route', '复制已追踪路径的链接'],
  'viewer.route.clear': ['Clear', '清除'],
  'viewer.route.clear.aria': ['Clear route probe', '清除路径探测'],
  'viewer.route.traced': ['Traced route', '已追踪路径'],
  'viewer.route.pickTwo': ['Pick two semantic nodes on the diagram', '在图表中选择两个语义节点'],
  'viewer.route.pickOne': ['Pick a semantic node on the diagram', '在图表中选择一个语义节点'],
  'viewer.route.controls': ['Route journey controls', '路径旅程控制'],
  'viewer.route.previous': ['Previous route position', '上一个路径位置'],
  'viewer.route.play': ['Play route journey', '播放路径旅程'],
  'viewer.route.pause': ['Pause route journey', '暂停路径旅程'],
  'viewer.route.replay': ['Replay route journey', '重播路径旅程'],
  'viewer.route.next': ['Next route position', '下一个路径位置'],
  'viewer.route.journey': ['Journey', '旅程'],
  'viewer.route.pause.label': ['Pause', '暂停'],
  'viewer.route.replay.label': ['Replay', '重播'],
  'viewer.route.overview': ['Overview', '总览'],
  'viewer.route.overview.aria': ['Show complete route overview', '显示完整路径总览'],
  'viewer.route.instructions': ['Choose the source, then the destination. Direction matters.', '先选择来源，再选择目标；方向很重要。'],
  'viewer.route.destination': ['Choose a destination from {label}', '选择从{label}出发的目标'],
  'viewer.route.destination.find': ['Find target', '查找目标'],
  'viewer.route.destination.find.aria': ['Find a reachable route destination', '查找可达的路径目标'],
  'viewer.route.differentDestination': ['Choose a different destination', '选择其他目标'],
  'viewer.route.distinct': ['A route needs two distinct semantic nodes.', '一条路径需要两个不同的语义节点。'],
  'viewer.route.unreachable': ['No directed route to {label}', '没有通往{label}的有向路径'],
  'viewer.route.unreachable.detail': ['{target} is not reachable from {source}. Pick a highlighted destination.', '从{source}无法到达{target}。请选择高亮的目标。'],
  'viewer.route.start.instructions': ['Select the source. The next step will reveal only directed destinations.', '选择来源。下一步只会显示有向可达的目标。'],
  'viewer.route.copy.success': ['Traced route link copied', '已复制路径链接'],
  'viewer.route.copy.failed': ['Could not copy traced route link', '无法复制路径链接'],
  'viewer.route.position': ['Route position {index} of {total}: {label}', '路径位置 {index}/{total}：{label}'],
  'viewer.route.step': ['Step {index} of {total} · {phase} · {label}', '第 {index}/{total} 步 · {phase} · {label}'],
  'viewer.route.motionRequired': ['Automatic journey requires Live motion', '自动旅程需要动态模式'],
  'viewer.route.trigger.clear': ['Clear traced route', '清除已追踪路径'],
  'viewer.route.overview.status': ['{nodes} · {hops} · shortest authored route', '{nodes} · {hops} · 最短编写路径'],
  'viewer.route.overview.node.one': ['{count} node', '{count} 个节点'],
  'viewer.route.overview.node.other': ['{count} nodes', '{count} 个节点'],
  'viewer.route.overview.hop.one': ['{count} directed hop', '{count} 个有向跳转'],
  'viewer.route.overview.hop.other': ['{count} directed hops', '{count} 个有向跳转'],
  'viewer.route.phase.playing': ['Playing', '播放中'],
  'viewer.route.phase.complete': ['Complete', '已完成'],
  'viewer.route.phase.inspecting': ['Inspecting', '检查中'],
  'viewer.route.destination.count.one': ['{count} directed destination available. Pick a highlighted node.', '有 {count} 个有向目标可用。请选择高亮节点。'],
  'viewer.route.destination.count.other': ['{count} directed destinations available. Pick a highlighted node.', '有 {count} 个有向目标可用。请选择高亮节点。'],
  'viewer.route.noOutgoing': ['No outgoing route starts here. Clear and choose another source.', '此处没有可用的出向路径。请清除后选择其他来源。'],
  'viewer.route.result.title': ['{source} to {target}', '{source} 到 {target}'],
  'viewer.route.finder.source.title': ['Choose route start', '选择路径起点'],
  'viewer.route.finder.source.placeholder': ['Search route sources', '搜索路径来源'],
  'viewer.route.finder.source.empty': ['No matching route sources', '没有匹配的路径来源'],
  'viewer.route.finder.source.results': ['Nodes that can start a route', '可作为路径起点的节点'],
  'viewer.route.finder.source.noun': ['route sources', '个路径来源'],
  'viewer.route.finder.source.badge': ['start', '起点'],
  'viewer.route.finder.target.title': ['Destination from {label}', '从{label}出发的目标'],
  'viewer.route.finder.target.placeholder': ['Search reachable destinations', '搜索可达目标'],
  'viewer.route.finder.target.empty': ['No matching reachable destinations', '没有匹配的可达目标'],
  'viewer.route.finder.target.results': ['Reachable route destinations', '可达路径目标'],
  'viewer.route.finder.target.noun': ['reachable destinations', '个可达目标'],
  'viewer.route.hop.one': ['{count} hop', '{count} 跳'],
  'viewer.route.hop.other': ['{count} hops', '{count} 跳'],


  'viewer.radar.title': ['Semantic radar', '语义雷达'],
  'viewer.radar.building': ['Building overview', '正在构建总览'],
  'viewer.radar.openFull': ['Open full semantic radar', '打开完整语义雷达'],
  'viewer.radar.open': ['Open radar', '打开雷达'],
  'viewer.radar.close': ['Close semantic radar', '关闭语义雷达'],
  'viewer.radar.surface': ['Diagram overview. Click a node to focus it, or use arrow keys to pan.', '图表总览。点击节点进行聚焦，或使用方向键平移。'],
  'viewer.radar.click': ['Click node', '点击节点'],
  'viewer.radar.drag': ['Drag to pan', '拖动平移'],
  'viewer.radar.space': ['Semantic radar needs more MAP space.', '语义雷达需要更多地图可见空间。'],
  'viewer.radar.nodes': ['Semantic diagram radar nodes', '语义图表雷达节点'],
  'viewer.radar.focus': ['Focus {label} from Semantic Radar', '从语义雷达聚焦{label}'],
  'viewer.radar.status': ['{count} nodes · {viewport}', '{count} 个节点 · {viewport}'],
  'viewer.radar.fullMap': ['{count} nodes · full map', '{count} 个节点 · 完整地图'],
  'viewer.radar.compacted': ['Radar compacted to avoid covering the Semantic Passport or MAP controls.', '已收紧雷达，避免遮挡语义护照或地图控件。'],
  'viewer.radar.cancelWaiting': ['Cancel semantic radar waiting for more MAP space', '取消等待更多地图空间的语义雷达'],
  'viewer.radar.needsSpace': ['Semantic radar needs more visible MAP space', '语义雷达需要更多可见地图空间'],
  'viewer.radar.viewport.full': ['full map', '完整地图'],
  'viewer.radar.viewport.width': ['{percent}% width', '宽度 {percent}%'],
  'viewer.radar.viewport.scale': ['{percent}% viewport', '视口 {percent}%'],

  'viewer.nav.controls': ['Diagram view controls', '图表视图控制'],
  'viewer.nav.route': ['Trace a directed route', '追踪有向路径'],
  'viewer.nav.route.title': ['Trace route (R)', '追踪路径（R）'],
  'viewer.nav.route.short': ['PATH', '路径'],
  'viewer.nav.radar': ['Open semantic radar', '打开语义雷达'],
  'viewer.nav.radar.title': ['Semantic radar (M)', '语义雷达（M）'],
  'viewer.nav.radar.short': ['MAP', '地图'],
  'viewer.nav.find': ['Find a node', '查找节点'],
  'viewer.nav.find.title': ['Find a node (/)', '查找节点（/）'],
  'viewer.nav.zoomOut': ['Zoom out', '缩小'],
  'viewer.nav.zoomOut.title': ['Zoom out (-)', '缩小（-）'],
  'viewer.nav.reset': ['Reset diagram view', '重置图表视图'],
  'viewer.nav.reset.title': ['Reset view (0)', '重置视图（0）'],
  'viewer.nav.read': ['READ', '阅读'],
  'viewer.nav.zoomIn': ['Zoom in', '放大'],
  'viewer.nav.zoomIn.title': ['Zoom in (+)', '放大（+）'],
  'viewer.nav.camera': ['{hint}. Reset diagram view', '{hint}。重置图表视图'],
  'viewer.nav.camera.title': ['{semantic}{hint} · reset view (0)', '{semantic}{hint} · 重置视图（0）'],
  'viewer.nav.camera.semantic': ['Semantic camera active · ', '语义相机已启用 · '],
  'viewer.nav.level.map': ['MAP', '概览'],
  'viewer.nav.level.read': ['READ', '阅读'],
  'viewer.nav.level.full': ['FULL', '完整'],
  'viewer.nav.level.auto': ['AUTO', '自动'],
  'viewer.nav.detail.map': ['Zoom in to reveal relationship labels and node context', '放大以显示关系标签和节点上下文'],
  'viewer.nav.detail.read': ['Zoom in again to reveal tags and annotations', '再次放大以显示标签和注释'],
  'viewer.nav.detail.full': ['Full diagram detail', '完整图表详情'],

  'viewer.intent.summary': ['{label}. {out} outgoing, {in} incoming{loops}. {total} connections. Press Enter for details.', '{label}。{out} 条出向，{in} 条入向{loops}。共 {total} 条连接。按 Enter 查看详情。'],
  'viewer.intent.loops': [', {count} self loop', '，{count} 条自环'],

  'viewer.common.copied': ['Copied', '已复制'],
  'viewer.common.copyFailed': ['Copy failed', '复制失败'],
  'viewer.common.copyLink': ['Copy link', '复制链接'],
  'viewer.common.clear': ['Clear', '清除'],
  'viewer.common.close': ['Close', '关闭'],
};

for (const [key, messages] of Object.entries(MESSAGE_PAIRS)) {
  if (messages.length !== SUPPORTED_LOCALES.length || messages.some((message) => typeof message !== 'string')) {
    throw new Error(`Incomplete Archify i18n tuple ${JSON.stringify(key)}`);
  }
}

const CATALOGS = Object.fromEntries(SUPPORTED_LOCALES.map((locale, index) => [
  locale,
  Object.fromEntries(Object.entries(MESSAGE_PAIRS).map(([key, pair]) => [key, pair[index]])),
]));

export function resolveLocale(locale) {
  return SUPPORTED_LOCALES.includes(locale) ? locale : DEFAULT_LOCALE;
}

export function formatMessage(template, values = {}) {
  return String(template).replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key) => (
    Object.hasOwn(values, key) ? String(values[key]) : match
  ));
}

export function translateMessage(locale, key, values = {}) {
  const resolved = resolveLocale(locale);
  if (!Object.hasOwn(CATALOGS[resolved], key)) {
    throw new Error(`Missing Archify i18n message ${JSON.stringify(key)} for ${resolved}`);
  }
  return formatMessage(CATALOGS[resolved][key], values);
}

export function translateCount(locale, key, count, values = {}) {
  const suffix = count === 1 ? 'one' : 'other';
  return translateMessage(locale, `${key}.${suffix}`, { ...values, count });
}

export function viewerCatalog(locale) {
  const resolved = resolveLocale(locale);
  return Object.fromEntries(Object.entries(CATALOGS[resolved]).filter(([key]) => key.startsWith('viewer.')));
}

export function localizeTemplate(template, locale) {
  return template.replace(/\{\{i18n:([a-zA-Z0-9_.-]+)\}\}/g, (_match, key) => escapeHtml(translateMessage(locale, key)));
}

export function catalogKeys() {
  return Object.keys(MESSAGE_PAIRS);
}
